### PR TITLE
Fixed RN 0.47 compatibility by removing @override from createJSModules

### PR DESCRIPTION
**Pull request by michalmmm**
Could not remove the function as it would break RN <0.47

### CODE REVIEW

**Comment by danny-does-stuff** [comment]
Please accept this MR! Made my project work with RN 0.47.2

**Comment by mvayngrib** [comment]
@dannyharding10 thanks for the PR, sorry for the wait! 
@michalmmm thanks for the reminder!

released as 1.5.0 in case it by some evil miracle this breaks something for someone with an earlier RN (it didn't break anything for me)

**Comment by danny-does-stuff** [comment]
Thanks for the credit, but it was actually @michalmmm who made the PR! Thanks for merging!

**Comment by michalmmm** [comment]
Thanks @dannyharding10 @mvayngrib !

**Pull request merged**
